<html>
<head>
 
<?php
		
		$this->headScript()->appendFile(HTTP_HOST.'/js/jquery.cookie.js');
		$this->headScript()->appendFile(HTTP_HOST.'/js/jquery.watermarkinput.js');
		$this->headScript()->appendFile(HTTP_HOST.'/js/jquery.treeview.js');
		$this->headScript()->appendFile(HTTP_HOST.'/js/chatroom.js');
		$this->headLink()->appendStylesheet(HTTP_HOST.'/css/jquery.treeview.css');
		$this->headLink()->appendStylesheet(HTTP_HOST.'/css/chatroom.css');

		//$this->headLink()->appendStylesheet(HTTP_HOST.'/css/screen.css');
?>

</head>

<body>


	<h1>Chat Room</h1>
	
	<div class="content">

<?php echo $this->schoolMenu($this->schools);?>	
	<div id="container" style="width:100% ;">
 
	<div id="menu" style="width: 30%;  float:left;">
	<?php echo $this->schoolTreeMenu($this->states,$this->user);?>	
 
	</div>	
	<div id="content" style="width: 70%; float:left;">
				<h2><?php  echo $this->currentschool;?></h2>
 				 
				<input type="text" name="search" id="comment" value="" /> 
				<input type="button" name="submit" id="submit_comment" value="Post" />
				 
 				<div id="activity" style="width:600px; overflow: visable" >
				<?php
				foreach ($this->activity as $value){
					if(strlen($value["sentence"])>5)
					echo $value["sentence"]."</br>";
				}
				?>
				</div>
	</div>
	
	<div id="footer" style="clear:both;text-align:left;"> <br/>
	 </div>
	
	</div>
	</div>
 </body>
</html>
