<?php echo $this->doctype() ?>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
  	<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
  	<meta name="robots" content="noodp,noydir" /> 
  	<?php 
  	
  	$this->headLink()->prependStylesheet(HTTP_HOST.'/css/sc.css')
  	->prependStylesheet(HTTP_HOST.'/css/jquery-ui.css');
  					
  					
    $this->headScript()->prependFile(HTTP_HOST.'/js/jquery-ui.js') //3rd
    					->prependFile(HTTP_HOST.'/js/jquery.js') //2nd
    					->prependFile(HTTP_HOST.'/js/jquery.watermarkinput.js') //2nd
    					->prependScript("HTTP_HOST = '".HTTP_HOST."';"); //1st
    
    
  	?>
  	<?php 
  		
  		echo $this->headScript();
  		echo $this->headLink();
  	?>
</head>
<body>


	<div class="parentStyle">
		<div class="logoStyle" style="float:left">
			ConnectStudents<span style="color:red;">.</span>
		</div>
		<div style="float:right"><a href="/connect/public/chatroom/chat" class="headera">Chat</a>
			<a href="/connect/public/profile/profile" class="headera">Profile</a>
			<a href="#" class="headera">Academics</a>
			<a href="?logout=true" style="text-decoration:none;margin-left:12px;color:white;border:2px solid white;padding:0 5px 0 5px">X</a></div>
			<div style="clear:both"></div>
		</div>
		
		<div class="pageStyle">			
			<?php echo $this->layout()->content ?>
		</div>
	</div>
		
</body>
</html>